[package]
name = "cmm"
version = "0.1.0"
edition = "2021"
authors = ["Reticence Ji"]
description = "C-- compiler"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sugars = "3.0"
pest = "2.0"
pest_derive = "2.0"
clap = { version = "3.1", features = ["derive"] }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
    "llvm10-0",
] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
