[package]
name = "rcc"
version = "0.1.0"
edition = "2021"
authors = ["Reticence Ji"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.0"
pest_derive = "2.0"
clap = { version = "3.1", features = ["derive"] }
