[package]
name = "cmm"
version = "0.1.0"
edition = "2021"
authors = ["Reticence Ji"]
description = "C-- compiler"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sugars = "3.0"
pest = "2.0"
pest_derive = "2.0"
clap = { version = "3.1", features = ["derive"] }
